package.json, package.nls.de.json, package.nls.json, src/sidebar/setupSidebar.ts, src/treeviews/WsList/WsList.interface.ts, src/treeviews/WsList/WsList.ts, src/treeviews/WsList/WsListItem.ts, src/treeviews/WsList/WsListItemActive.ts, src/treeviews/WsList/WsListItemError.ts, src/treeviews/WsList/WsListItemErrorSub.ts, src/treeviews/WsList/WsListItemLoading.ts
=> feat(sidebar): display path to ws file

src/constants/fs.ts, src/sidebar/setupSidebar.ts, src/treeviews/WsList/WsList.ts, src/utils/fs/isWorkspacefile.ts
Detects if a WS file is created and if it is, clears the caches and recollects the ws files
=> feat(sidebar): update cache/ui if ws file created

package.nls.de.json
Here you go (:
Let me know if something is missing.
=> Improved german translation.

.stylelintrc, package.json, src/config/getConfig.ts, src/constants/config.ts, src/templates/workspace/snippets/tree.ts, src/templates/workspace/snippets/treeItemFile.ts, src/test/suite/config/getConfig.test.ts, src/test/suite/templates/workspace/snippets/tree.test.ts, src/test/suite/webviews/Workspace/helpers/getVisibleFiles.test.ts, src/webviews/registerWebviews.ts, yarn.lock
=> feat: display root folder in tree via config

src/test/mocks/mockFileData.ts, src/test/mocks/mockRenderVars.ts, src/test/mocks/mockTemplateVars.ts, src/test/suite/theme/getLangIcon.test.ts, src/test/suite/utils/fs/getLastPathSegment.test.ts, src/test/suite/utils/fs/isSelected.test.ts, src/test/suite/webviews/Workspace/helpers/convertWsFiles.test.ts, src/test/suite/webviews/Workspace/helpers/getLabel.test.ts, src/test/suite/webviews/Workspace/helpers/getPath.test.ts, src/test/suite/webviews/Workspace/store/setFileTree.test.ts, src/utils/fs/isSelected.ts, src/utils/os/isWindows.ts, src/webviews/Workspace/helpers/convertWsFiles.ts, src/webviews/Workspace/helpers/getPath.ts
- Fix tests so that they run without issue on windows
=> test: fix for windows

src/test/suite/webviews/Workspace/store/toggleFolderStateBulk.test.ts, src/webviews/Workspace/store/toggleFolderStateBulk.ts
- Bulk open did not work if some subfolders were open
=> fix: bulk open issue

package.json, src/webviews/Workspace/WorkspaceViewProvider.interface.ts, src/webviews/Workspace/WorkspaceViewProvider.ts
Closes #99 
- Added version to webview
- Updated interfaces for storage
=> feat(99): link cache to version

package.json, yarn.lock
- Fixes #112 
- Changes made to key cleaning in file theme processor package. Package updated here
=> fix(112): icon css

package.json, src/webviews/Workspace/WorkspaceViewProvider.interface.ts, src/webviews/Workspace/WorkspaceViewProvider.ts, src/webviews/registerWebviews.ts, yarn.lock
*Closes: #95*
- Changed rootFolders from application sciope to machine
- rootFolders is now no longer synced
- Can use machine settings for remotes (ssh)
- Not possible to have different configs per profile since the API does not give anyway to tell what profile is being used. See: https://github.com/microsoft/vscode/issues/177463
=> feat(config): support remote config for folders

README.md, src/config/folders.ts, src/templates/helpers/getDescription.ts, src/templates/helpers/getFileTooltip.ts, src/templates/workspace/snippets/itemFile.ts, src/test/mocks/mockExtensionUri.ts, src/test/suite/config/core.test.ts, src/test/suite/config/folders.test.ts, src/test/suite/config/general.test.ts, src/test/suite/config/listview.test.ts, src/test/suite/config/search.test.ts, src/test/suite/config/treeview.test.ts, src/test/suite/templates/helpers/getDescription.test.ts, src/test/suite/templates/helpers/getFileTooltip.test.ts, src/test/suite/webviews/Workspace/helpers/getNewRootFolderConfig.test.ts, src/webviews/Workspace/WorkspaceViewProvider.ts, src/webviews/Workspace/helpers/getNewRootFolderConfig.ts, src/webviews/Workspace/helpers/getVisibleFiles.ts, src/webviews/Workspace/store/fetch.ts
=> feat(123): various bug fixes

README.md, package.json, src/templates/workspace/snippets/itemFolder.ts, src/test/suite/templates/workspace/snippets/itemFolder.test.ts
Closes: #127 
- Updated docs
- Identified issue with check for selected folder - problem fixed
- Updated tests
=> fix(127): mutiple folders marked as selected

README.md, src/templates/workspace/snippets/list.ts, src/templates/workspace/views/listView.ts, src/test/suite/templates/workspace/snippets/externalWorkspace.test.ts, src/test/suite/templates/workspace/snippets/folderListItem.test.ts, src/test/suite/templates/workspace/snippets/hoverNotification.test.ts, src/test/suite/templates/workspace/snippets/list.test.ts, src/test/suite/templates/workspace/snippets/searchForm.test.ts, src/test/suite/templates/workspace/views/listView.test.ts
Closes #124 
- Removed empty rendering on list view since this now can't happen.
=> fix(124): fixed issue with list view and all folders having errors

.github/workflows/publish.yml
=> chore: update release action

.github/workflows/publish.yml
=> chore: update publish action

.github/workflows/publish.yml
=> chore: typo

package.json, src/webviews/configOptions.ts, src/webviews/registerWebviews.ts
Closes #147 
- Moved explorer congig check outside of workspaceSidebar checks
- Updated package version to 2.0.2
=> feat(config): improve explorer config watch

package.nls.de.json, package.nls.json, src/templates/workspace/views/loadingView.ts, src/test/suite/templates/workspace/views/loadingView.test.ts
=> chore: update template

scripts/change_version.sh
=> chore: change script

package.json, package.nls.de.json, package.nls.json, src/config/general.ts, src/constants/commands.ts, src/constants/config.ts, src/test/suite/config/general.test.ts, src/webviews/Workspace/WorkspaceViewProvider.ts
Closes #173 
- Added new config option
- Added translations for config option
- Focus explorer view after opening a ws in a new window
=> feat(173): add new config to focus explorer view

README.md, src/templates/helpers/isExternalWs.ts, src/test/mocks/mockState.ts, src/test/suite/config/folders.test.ts, src/test/suite/templates/helpers/isExternalWs.test.ts, src/test/suite/webviews/Workspace/helpers/getFileTree.test.ts, src/test/suite/webviews/Workspace/helpers/updateByType.test.ts, src/test/suite/webviews/Workspace/store/fetch.test.ts, src/test/suite/webviews/Workspace/store/list.test.ts, src/test/suite/webviews/Workspace/store/setFileTree.test.ts, src/test/suite/webviews/Workspace/store/setRootFolders.test.ts, src/test/suite/webviews/Workspace/store/setSearch.test.ts, src/test/suite/webviews/Workspace/store/setVisibleFiles.test.ts, src/test/suite/webviews/Workspace/store/workspaceSlice.test.ts, src/webviews/Workspace/helpers/updateByType.ts, src/webviews/Workspace/store/initialStates.ts, src/webviews/registerWebviews.ts
=> test: fix tests for 2.1.0

src/webviews/Workspace/store/list.ts
Closes #197 
- Check folderPath status and set the correct result in the root folder.
=> fix(197): list reducer shows wrong result

CHANGELOG.md, README.md, docs/Configuration.md, docs/File Icon Themes.md
Close #194 
- UPdate docs for v2.1.0
=> Docs/194 update for v2.1.0

CHANGELOG.md, README.md, package.json, src/webviews/Workspace/WorkspaceViewProvider.ts, yarn.lock
Closes #204 
Closes #205 
- Always re-render whenever file theme processor state changes
- Use v1.0.8 of file theme processor
=> fix(fileicons): loading issues fxed
